package com.ing.casyadapterpoc.tracking;

public enum Action {

    GET_SINGLE_ACCOUNT, GET_MULTIPLE_ACCOUNTS,
    GET_SINGLE_TRANSACTIONS, GET_MULTIPLE_TRANSACTIONS,
    CREATE_USER, DELETE_USER,
    GRANT_ACTIVATION, REFRESH, GRANT_DELETION
}
